language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install

script:
  - phpunit
  - vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run
